sudo: false
matrix:
  fast_finish: true
  include:
  - python: '3.6'
    env: TOXENV=py36
  - python: '3.7'
    env: TOXENV=py37
  - python: '3.8'
    env: TOXENV=py38
cache:
  directories:
  - "$HOME/.cache/pip"
language: python
before_install: python -m pip install --upgrade pip
install: pip install -U tox-travis
script: travis_wait 30 tox --develop
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: awarecan
  password:
    secure: XzYz7NMpUgb12a6AoTPkb4PIhMMtA+s0wThBJ4cQ1y9zHG4tM7WWhXec0DAJgWTjFXYU0u064Evk2kystw15VDx5F1xIaUsqyHeLe7VhhQJicbhfZYY28lPNPEPV3aNcIayKhu19M9wv4VRgR4RJ0HfFLbV/5hQB/O8V7xLAqDwDU+g4GYJq31rJjNgWlB9iCbH84zrtrYTIwJzfv+NSp51ocVtN45LElt3/5AKDAV+cmfCXAEAw9MfeNIdXvlNWVvr/HSP2t4gRw05K/OipeZlV0zX80YOBViNoYbYiFz0skBi1h+m/xWTp3ZcExI8G7YBrTkMmyFAVS1/ZbkpudaODmSFng0HmUEZbuY3BUAOQpJkNr9fUbUQyk5BSes6r2DTQQRHVFM49GOXVNf9wOtRojG8gu6L1yJfWlW86133DUng3EDxOn98Fdm06467KIZmbd6WiZjEtmUJublWAEVc4VWHtuaFj3hKQ05c/IqLDHr9itIhKGVpU5vkywUf9Qcq5sfMeKdkTveH61aodN0kMZhXMCnoXfcFrsXoS3Doy0sTfRlNtn5JyJfxw5dqcLpAusb14YXFTiy412NMKtnnOKNdt35h2NnOGWjziaGZrrc0qTWWAXLfnu+LA2gH+UUCPsTMWBa4rxELa3kPs4wf4gKEh+O4M5fKesuMAdiE=
  on:
    tags: true
    repo: rtfol/aiohttp-sse-client
    python: 3.6
